name: Code quality

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: code-quality-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: zulu
          java-version: 21

      - name: Cache Kotlin/Native
        uses: ./.github/actions/cache-kotlin-native
        with:
          save: ${{ github.ref == 'refs/heads/main' }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Check formatting
        run: ./gradlew spotlessCheck

      - name: Check public API
        run: ./gradlew checkKotlinAbi

      - name: Build, analyse and test
        run: ./gradlew build

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: reports
          path: |
            **/build/reports/**
            **/build/test-results/**
          retention-days: 7
